### ISSUE TITLE
[Lightwave Binding] Is this message killing the receiver socket?

### ISSUE THREAD

**Issue by foxy82** [foxy82/openhab#21]
2015-12-13 00:06:51.189 DEBUG o.o.b.l.i.LightwaveRFReceiverThread[:126]- Message received from: /192.168.1.50 message:*?{"trans":213454,"mac":"03:02:71","cmd":"get_duskdawn","lat":51.52,"long":-0.08,"offset":0}

**Comment by davidsnyders** [comment]
I'm not sure what message causes it because I don't see anything in my log.  However the EnergyMonitor always fails a few minutes after midnight for the last few days.
After restarting, it then works fine for the rest of the day

**Comment by foxy82** [comment]
Hey - yeah it was that message. I've fixed and pushed a new version:

https://github.com/foxy82/openhab/releases/tag/1.8.0_alpha8

Also if you test this and it works can you comment on this pull request so I can get it merged into the Openhab main repository:

https://github.com/openhab/openhab/pull/3457

Thanks.
