### ISSUE TITLE
Spaces in Lightwave commands not being sent by OpenHAB binding

### ISSUE THREAD

**Issue by proffalken** [foxy82/openhab#29]
Hi all,

I have the lightwaverf wifi link (the new one without the LCD) and I have noticed that when trying to sniff the packets on the wire whilst using my phone to control my lights, there appears to be an additional space inserted into the format of the message.

Instead of the message being formatted as documented on the wiki "nnnnnn,100,!R1D3F1" (where 'nnnnnn' is the unique identifier for my android phone app in the UDP packet), there is a space between the R and the Room identifier:

"nnnnnn,100,!R 1D3F1"

Try as I might, I am unable to replicate this in the configuration. If I place a space in the appropriate character slot, then the binding simply ignores it and tries to dim a light on ""nnnnnn,100,!RD3F1".

Is anyone able to shed light on why this might be and how to fix it?

Thanks in advance,

Matt

P.S. I posted this on the forums at https://community.openhab.org/t/lightwave-rf-udp-packets-are-not-formatted-correctly/8116 however I wasn't sure if I should post it here as well, please feel free to tell me which one to close/delete :)

**Comment by foxy82** [comment]
I've replied on the forum - let me know how you get on.

**Comment by proffalken** [comment]
Closing this, it was a formatting error in tcpdump output, apologies for taking so long to do so!
